version: '2'

services:
  website: 
    build: .
    command: >
      gunicorn -p 8000:8000 -b 0.0.0.0:8000 --access-logfile - --reload "snakeeyes.app:create_app()"
    environment: 
      PYTHONBUFFERED: 'true'
    volumes: 
      - '.:/snakeeyes'
    ports: 
      - '8000:8000'
     
